### ISSUE TITLE
Detailed PSI stats

### ISSUE THREAD

**Issue by burnflare** [nikhilsh/PSIBar#2]
Feature request: Clicking on the menu bar icon reveals a list like:
-- Air quality right now(Good, moderate, unhealthy, etc) --
-- 24 hr PSI --
-- 3 hr PSI --
-- North PSI --
-- East PSI --
-- South PSI --
-- West PSI --

**Comment by nikhilsh** [comment]
fixed in 705586c36cd610943926b629ef37eb937769bf4c
